---
- include: oracle_java_setup.yml
  when: java_versions is defined and java_versions is sequence and java_versions|join|search("oracle")

- include: oracle_java_install.yml
  when: java_versions is defined and java_versions is sequence and java_versions|join|search("openjdk")